FROM node:22-alpine

WORKDIR /workspace

COPY frontend/package.json frontend/package-lock.json ./
COPY frontend/apps ./apps
COPY frontend/packages ./packages
COPY frontend/postcss.config.cjs ./postcss.config.cjs
COPY frontend/tailwind.config.cjs ./tailwind.config.cjs
COPY frontend/tsconfig.base.json ./tsconfig.base.json

RUN npm install

EXPOSE 5173 5174
