# Generated by Django 6.0.3 on 2026-04-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_no", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(choices=[("pending_payment", "待支付"), ("paid", "已支付"), ("confirmed", "已确认"), ("checked_in", "已入住"), ("completed", "已完成"), ("cancelled", "已取消"), ("refunding", "退款中"), ("refunded", "已退款")], default="pending_payment", max_length=32)),
                ("payment_status", models.CharField(choices=[("unpaid", "未支付"), ("paid", "已支付"), ("failed", "支付失败"), ("refunded", "已退款")], default="unpaid", max_length=32)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_mobile", models.CharField(max_length=20)),
                ("guest_count", models.PositiveIntegerField(default=1)),
                ("room_no", models.CharField(blank=True, max_length=20)),
                ("remark", models.CharField(blank=True, max_length=255)),
                ("operator_remark", models.CharField(blank=True, max_length=255)),
                ("original_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("pay_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hotel", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="booking_orders", to="hotels.hotel")),
                ("room_type", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="booking_orders", to="hotels.roomtype")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="booking_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Booking Order",
                "verbose_name_plural": "Booking Orders",
                "ordering": ["-id"],
            },
        ),
    ]
