# Generated by Django 6.0.3 on 2026-04-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.usercoupon'),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='优惠券减免', max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='member_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='会员折扣减免', max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingorder',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='本单获得积分'),
        ),
    ]
