# Generated by Django 6.0.3 on 2026-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_bookingorder_coupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
