# Generated by Django 6.0.3 on 2026-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bookingorder_status_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingorder",
            name="check_in_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bookingorder",
            name="check_out_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="bookingorder",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "未支付"),
                    ("paid", "已支付"),
                    ("failed", "支付失败"),
                    ("refunded", "已退款"),
                ],
                db_index=True,
                default="unpaid",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="bookingorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "待支付"),
                    ("paid", "已支付"),
                    ("confirmed", "已确认"),
                    ("checked_in", "已入住"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refunding", "退款中"),
                    ("refunded", "已退款"),
                ],
                db_index=True,
                default="pending_payment",
                max_length=32,
            ),
        ),
    ]
