# Generated by Django 6.0.3 on 2026-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingorder_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunding', '退款中'), ('refunded', '已退款')], db_index=True, default='unpaid', max_length=32),
        ),
    ]
