# Generated by Django 6.0.3 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_payment_refunding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
