# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_bookingorder_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingorder",
            name="member_points_earned",
            field=models.PositiveIntegerField(default=0, help_text="本单累计会员积分"),
        ),
        migrations.AlterField(
            model_name="bookingorder",
            name="points_earned",
            field=models.PositiveIntegerField(default=0, help_text="本单获得消费积分"),
        ),
    ]
