# Generated by Django 6.0.3 on 2026-04-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("avatar", models.URLField(blank=True)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("gender", models.CharField(choices=[("unknown", "未知"), ("male", "男"), ("female", "女")], default="unknown", max_length=20)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("role", models.CharField(choices=[("user", "普通用户"), ("hotel_admin", "酒店管理员"), ("system_admin", "系统管理员")], default="user", max_length=32)),
                ("status", models.CharField(choices=[("active", "正常"), ("disabled", "禁用"), ("locked", "锁定")], default="active", max_length=32)),
                ("member_level", models.CharField(choices=[("normal", "普通会员"), ("silver", "银卡会员"), ("gold", "金卡会员"), ("platinum", "白金会员")], default="normal", max_length=32)),
                ("points", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
