# Generated by Django 6.0.3 on 2026-04-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='member_level',
            field=models.CharField(choices=[('normal', '普通会员'), ('silver', '银卡会员'), ('gold', '金卡会员'), ('platinum', '铂金会员'), ('diamond', '钻石会员')], default='normal', max_length=32),
        ),
    ]
