# Generated by Codex on 2026-05-10

from django.db import migrations, models


def copy_legacy_points(apps, schema_editor):
    """Initialize split point balances from the legacy points column."""

    UserProfile = apps.get_model("users", "UserProfile")
    for profile in UserProfile.objects.all().only("id", "points"):
        legacy_points = max(int(profile.points or 0), 0)
        profile.member_points = legacy_points
        profile.consume_points = legacy_points
        profile.save(update_fields=["member_points", "consume_points"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_member_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="consume_points",
            field=models.PositiveIntegerField(default=0, help_text="消费积分余额，可用于兑换优惠券或礼品"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="member_points",
            field=models.PositiveIntegerField(default=0, help_text="会员成长积分，只增不减，用于等级升级"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="points",
            field=models.PositiveIntegerField(default=0, help_text="兼容旧接口的消费积分余额"),
        ),
        migrations.RunPython(copy_legacy_points, migrations.RunPython.noop),
    ]
