# Generated by Django 6.0.3 on 2026-04-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=100)),
                ("target", models.CharField(blank=True, max_length=100)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="audit_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SystemNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notice_type", models.CharField(choices=[("order", "订单通知"), ("payment", "支付通知"), ("activity", "活动通知"), ("system", "系统通知"), ("review", "评价通知")], default="system", max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="system_notices", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "System Notice",
                "verbose_name_plural": "System Notices",
                "ordering": ["-id"],
            },
        ),
    ]
