# Generated by Django 6.0.3 on 2026-04-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemnotice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("order", "订单通知"),
                    ("payment", "支付通知"),
                    ("activity", "活动通知"),
                    ("system", "系统通知"),
                    ("review", "评价通知"),
                    ("member", "会员通知"),
                    ("coupon", "优惠券通知"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
