# Generated by Django 6.0.3 on 2026-04-08 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_alter_systemnotice_notice_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene", models.CharField(help_text="AI 使用场景标识", max_length=50)),
                (
                    "provider",
                    models.CharField(help_text="AI 供应商名称", max_length=50),
                ),
                ("model", models.CharField(help_text="使用的模型名称", max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "cost_estimate",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="估算费用（元）",
                        max_digits=10,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="响应延迟（毫秒）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("quota_exceeded", "超额"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Call Log",
                "verbose_name_plural": "AI Call Logs",
                "ordering": ["-id"],
            },
        ),
    ]
