# Generated by Django 6.0.3 on 2026-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_add_ai_call_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(default="HoteLink 酒店管理系统", max_length=100),
                ),
                (
                    "admin_name",
                    models.CharField(default="HoteLink 管理端", max_length=100),
                ),
                (
                    "support_phone",
                    models.CharField(default="400-000-0000", max_length=30),
                ),
                ("order_auto_cancel_minutes", models.PositiveIntegerField(default=30)),
            ],
            options={
                "verbose_name": "Platform Config",
                "verbose_name_plural": "Platform Configs",
            },
        ),
    ]
