# Generated by Django 6.0.3 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_alter_aicalllog_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfig",
            name="support_email",
            field=models.EmailField(default="support@hotelink.com", max_length=254),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="business_hours",
            field=models.CharField(default="09:00-18:00", max_length=100),
        ),
        migrations.AddField(
            model_name="platformconfig",
            name="platform_notice",
            field=models.CharField(default="欢迎使用 HoteLink 酒店管理系统", max_length=255),
        ),
    ]