# Generated by Django 6.0.3 on 2026-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0008_expand_platform_config_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemnotice",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
