# Generated by Django 6.0.3 on 2026-04-20 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_systemnotice_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['scene', '-created_at'], name='idx_aicalllog_scene_created'),
        ),
        migrations.AddIndex(
            model_name='aicalllog',
            index=models.Index(fields=['status', '-created_at'], name='idx_aicalllog_status_created'),
        ),
    ]
