# Generated by Django 6.0.3 on 2026-05-10 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_alter_systemnotice_notice_type_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aicalllog",
            name="fallback_reason",
            field=models.CharField(
                blank=True, help_text="走兜底或规则路径的原因", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="aicalllog",
            name="llm_invoked",
            field=models.BooleanField(
                default=False, help_text="本次请求是否真实尝试调用了模型"
            ),
        ),
        migrations.AddField(
            model_name="aicalllog",
            name="result_source",
            field=models.CharField(
                choices=[
                    ("llm", "模型生成"),
                    ("fallback", "兜底结果"),
                    ("rule_engine", "规则引擎"),
                ],
                default="llm",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="aicalllog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "成功"),
                    ("fallback", "兜底"),
                    ("rule_based", "规则"),
                    ("failed", "失败"),
                    ("timeout", "超时"),
                    ("quota_exceeded", "超额"),
                ],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="aicalllog",
            index=models.Index(
                fields=["result_source", "-created_at"],
                name="idx_aicalllog_source_created",
            ),
        ),
    ]
