# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("star", models.PositiveSmallIntegerField(default=3)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.URLField(blank=True)),
                ("rating", models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ("min_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_recommended", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("draft", "草稿"), ("online", "已上架"), ("offline", "已下架")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("bed_type", models.CharField(choices=[("single", "单人床"), ("double", "双人床"), ("queen", "大床"), ("twin", "双床"), ("family", "家庭床")], default="queen", max_length=20)),
                ("area", models.PositiveIntegerField(default=20)),
                ("breakfast_count", models.PositiveIntegerField(default=0)),
                ("base_price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_guest_count", models.PositiveIntegerField(default=2)),
                ("stock", models.PositiveIntegerField(default=10)),
                ("status", models.CharField(choices=[("online", "已上架"), ("offline", "已下架")], default="online", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hotel", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="room_types", to="hotels.hotel")),
            ],
            options={
                "verbose_name": "Room Type",
                "verbose_name_plural": "Room Types",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="RoomInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("available", "空闲可售"), ("reserved", "已预订"), ("occupied", "在住"), ("cleaning", "清扫中"), ("maintenance", "维修中"), ("offline", "下线不可售")], default="available", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("room_type", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="inventories", to="hotels.roomtype")),
            ],
            options={
                "verbose_name": "Room Inventory",
                "verbose_name_plural": "Room Inventories",
                "ordering": ["date", "room_type_id"],
                "unique_together": {("room_type", "date")},
            },
        ),
    ]
