# Generated by Django 6.0.3 on 2026-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="images",
            field=models.JSONField(
                blank=True, default=list, help_text="酒店图片 URL 列表"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="image",
            field=models.URLField(blank=True, help_text="房型主图 URL"),
        ),
    ]
