# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_add_hotel_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name="roomtype",
            constraint=models.UniqueConstraint(fields=("hotel", "name"), name="uniq_room_type_name_per_hotel"),
        ),
    ]
