# Generated by Django 6.0.3 on 2026-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_hotel_name_unique_and_room_type_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="facilities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="设施标签列表，如 ['wifi','parking','pool']",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="自定义标签，如 ['免费取消','含早','近地铁']",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="type",
            field=models.CharField(
                choices=[
                    ("hotel", "酒店"),
                    ("homestay", "民宿"),
                    ("short_rent", "短租"),
                ],
                db_index=True,
                default="hotel",
                max_length=20,
            ),
        ),
    ]
