# Generated by Django 6.0.3 on 2026-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_hotel_facilities_hotel_tags_hotel_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roominventory",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="city",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("online", "已上架"),
                    ("offline", "已下架"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="roominventory",
            constraint=models.UniqueConstraint(
                fields=("room_type", "date"), name="uniq_roomtype_date"
            ),
        ),
    ]
