# Generated by Django 6.0.3 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_roominventory_unique_together_alter_hotel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='is_recommended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['hotel', 'status'], name='idx_roomtype_hotel_status'),
        ),
    ]
