# Generated by Django 6.0.3 on 2026-04-04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0001_initial"),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=120)),
                ("mobile", models.CharField(blank=True, max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="customer_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
            },
        ),
        migrations.CreateModel(
            name="FavoriteHotel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hotel", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorited_by", to="hotels.hotel")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="favorite_hotels", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Favorite Hotel",
                "verbose_name_plural": "Favorite Hotels",
                "ordering": ["-id"],
                "unique_together": {("user", "hotel")},
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveSmallIntegerField(default=5)),
                ("content", models.TextField()),
                ("reply_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hotel", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="reviews", to="hotels.hotel")),
                ("order", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="review", to="bookings.bookingorder")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("status", models.CharField(choices=[("unused", "未使用"), ("used", "已使用"), ("expired", "已过期")], default="unused", max_length=20)),
                ("valid_start", models.DateField()),
                ("valid_end", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="coupons", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "User Coupon",
                "verbose_name_plural": "User Coupons",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("invoice_type", models.CharField(choices=[("personal", "个人发票"), ("company", "企业发票")], default="personal", max_length=20)),
                ("title", models.CharField(max_length=150)),
                ("tax_no", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="invoice_titles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Invoice Title",
                "verbose_name_plural": "Invoice Titles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "待处理"), ("issued", "已开票"), ("cancelled", "已取消")], default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice_title", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="invoice_requests", to="crm.invoicetitle")),
                ("order", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="invoice_requests", to="bookings.bookingorder")),
            ],
            options={
                "verbose_name": "Invoice Request",
                "verbose_name_plural": "Invoice Requests",
                "ordering": ["-id"],
            },
        ),
    ]
