# Generated by Django 6.0.3 on 2026-04-07 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingorder_coupon_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coupon_type', models.CharField(choices=[('cash', '满减券'), ('discount', '折扣券')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='满减金额（cash类型时使用）', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=1, default=10, help_text='折扣值如9.5表示95折（discount类型时使用）', max_digits=3)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='最低消费门槛，0表示无门槛', max_digits=10)),
                ('total_count', models.PositiveIntegerField(default=100, help_text='总发行量')),
                ('claimed_count', models.PositiveIntegerField(default=0, help_text='已领取数量')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='每人限领')),
                ('required_level', models.CharField(blank=True, default='', help_text='所需最低会员等级，空表示不限', max_length=32)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='积分兑换成本，0表示免费领取')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '已下架')], default='active', max_length=20)),
                ('valid_days', models.PositiveIntegerField(default=30, help_text='领取后有效天数')),
                ('valid_start', models.DateField(help_text='活动开始日期')),
                ('valid_end', models.DateField(help_text='活动结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon Template',
                'verbose_name_plural': 'Coupon Templates',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='coupon_type',
            field=models.CharField(choices=[('cash', '满减券'), ('discount', '折扣券')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=10, help_text='折扣值', max_digits=3),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='最低消费门槛', max_digits=10),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='bookings.bookingorder'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='满减金额', max_digits=10),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to='crm.coupontemplate'),
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('consume_reward', '消费奖励'), ('review_reward', '评价奖励'), ('coupon_exchange', '积分兑券'), ('admin_adjust', '管理员调整'), ('level_up_gift', '升级礼包')], max_length=30)),
                ('points', models.IntegerField(help_text='正值为获得，负值为消耗')),
                ('balance', models.PositiveIntegerField(help_text='变动后积分余额')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_logs', to='bookings.bookingorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Log',
                'verbose_name_plural': 'Points Logs',
                'ordering': ['-id'],
            },
        ),
    ]
