# Generated by Django 6.0.3 on 2026-04-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_review_images"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="auto_tags",
            field=models.JSONField(
                blank=True, default=list, help_text="AI 自动生成的评价标签列表"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment_analyzed_at",
            field=models.DateTimeField(
                blank=True, help_text="最后一次 AI 情感分析时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment_keywords",
            field=models.JSONField(
                blank=True, default=list, help_text="AI 提取的关键词列表"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment_label",
            field=models.CharField(
                blank=True, help_text="positive / neutral / negative", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="sentiment_score",
            field=models.FloatField(
                blank=True, help_text="情感分数 0-1，0=极负面，1=极正面", null=True
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene",
                    models.CharField(
                        choices=[
                            ("customer_service", "智能客服"),
                            ("booking_assistant", "订房助手"),
                        ],
                        default="customer_service",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="会话标题（自动从首条消息提取）",
                        max_length=200,
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "助手"),
                            ("system", "系统"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0, help_text="本条消息消耗的 token 数（仅助手消息有值）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["id"],
            },
        ),
    ]
