# Generated by Django 6.0.3 on 2026-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_review_sentiment_fields_chat_session_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoupon",
            name="status",
            field=models.CharField(
                choices=[
                    ("unused", "未使用"),
                    ("used", "已使用"),
                    ("expired", "已过期"),
                ],
                db_index=True,
                default="unused",
                max_length=20,
            ),
        ),
    ]
