# Generated by Django 6.0.3 on 2026-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_usercoupon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='是否对外可见（管理员可隐藏评价）'),
        ),
    ]
