# Generated by Django 6.0.3 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_review_is_visible'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupontemplate',
            index=models.Index(fields=['status', 'valid_start', 'valid_end'], name='idx_coupon_tpl_active'),
        ),
    ]
