# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_coupontemplate_idx_coupon_tpl_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointslog",
            name="point_type",
            field=models.CharField(
                choices=[("consume", "消费积分"), ("member", "会员积分")],
                default="consume",
                max_length=20,
            ),
        ),
    ]
