"""apps/api/urls.py —— API v1 路由表，按公共/用户/管理端进行分组。"""

from django.urls import path

from apps.api.views import (
    AdminAIReportSummaryView,
    AdminAISettingsView,
    AdminAIProviderAddView,
    AdminAIProviderSwitchView,
    AdminAIProviderDeleteView,
    AdminAIReplySuggestionView,
    AdminAIReviewSummaryView,
    AdminCouponTemplatesView,
    AdminCouponTemplateUpdateView,
    AdminMemberOverviewView,
    AdminSystemResetView,
    SystemInitCheckView,
    SystemInitSetupView,
    AdminDashboardChartsView,
    AdminDashboardOverviewView,
    AdminEmployeesView,
    AdminHotelsView,
    AdminInventoryView,
    AdminOrdersChangeStatusView,
    AdminOrdersCheckInView,
    AdminOrdersCheckOutView,
    AdminOrdersDetailView,
    AdminOrdersView,
    AdminReportTasksView,
    AdminReviewsReplyView,
    AdminReviewsView,
    AdminRoomTypesView,
    AdminSettingsView,
    AdminUsersChangeStatusView,
    AdminUsersView,
    ApiRootView,
    CommonCitiesView,
    CommonDictsView,
    CommonImageThumbView,
    CommonUploadView,
    PublicHomeView,
    PublicHotelDetailView,
    PublicHotelSearchSuggestView,
    PublicHotelReviewsView,
    PublicHotelsView,
    PublicRoomTypeCalendarView,
    UserAIChatView,
    UserAIChatStreamView,
    UserAuthMeView,
    UserAvailableCouponsView,
    UserClaimCouponView,
    UserCouponsView,
    UserFavoritesView,
    UserInvoiceApplyView,
    UserInvoiceTitleCreateView,
    UserInvoicesView,
    UserOrderAvailableCouponsView,
    UserOrdersCancelView,
    UserOrdersCreateView,
    UserOrdersDetailView,
    UserOrdersPayView,
    UserOrderGuestHistoryView,
    UserOrdersUpdateView,
    UserOrdersView,
    UserPasswordChangeView,
    UserProfileView,
    UserProfileAvatarView,
    UserReviewsCreateView,
    UserNoticesView,
    UserNoticeUnreadCountView,
    UserPointsLogsView,
    UserRegisterView,
    UserLoginView,
    AdminLoginView,
    RefreshTokenApiView,
    LogoutApiView,
)

urlpatterns = [
    # 系统初始化与公共能力接口
    path("", ApiRootView.as_view(), name="api-root"),
    path("system/init-check", SystemInitCheckView.as_view(), name="system-init-check"),
    path("system/init-setup", SystemInitSetupView.as_view(), name="system-init-setup"),
    path("common/upload", CommonUploadView.as_view(), name="common-upload"),
    path("common/image-thumb", CommonImageThumbView.as_view(), name="common-image-thumb"),
    path("common/cities", CommonCitiesView.as_view(), name="common-cities"),
    path("common/dicts", CommonDictsView.as_view(), name="common-dicts"),
    # 公共查询接口
    path("public/home", PublicHomeView.as_view(), name="public-home"),
    path("public/hotels", PublicHotelsView.as_view(), name="public-hotels"),
    path("public/hotels/search-suggest", PublicHotelSearchSuggestView.as_view(), name="public-hotels-search-suggest"),
    path("public/hotels/detail", PublicHotelDetailView.as_view(), name="public-hotel-detail"),
    path("public/hotels/reviews", PublicHotelReviewsView.as_view(), name="public-hotel-reviews"),
    path("public/room-types/calendar", PublicRoomTypeCalendarView.as_view(), name="public-room-type-calendar"),
    path("public/auth/register", UserRegisterView.as_view(), name="public-register"),
    path("public/auth/login", UserLoginView.as_view(), name="public-login"),
    path("public/auth/admin-login", AdminLoginView.as_view(), name="public-admin-login"),
    path("public/auth/refresh", RefreshTokenApiView.as_view(), name="public-refresh"),
    # 用户端接口
    path("user/auth/logout", LogoutApiView.as_view(), name="user-logout"),
    path("user/auth/me", UserAuthMeView.as_view(), name="user-auth-me"),
    path("user/profile", UserProfileView.as_view(), name="user-profile"),
    path("user/profile/update", UserProfileView.as_view(), name="user-profile-update"),
    path("user/profile/avatar", UserProfileAvatarView.as_view(), name="user-profile-avatar"),
    path("user/profile/change-password", UserPasswordChangeView.as_view(), name="user-profile-change-password"),
    path("user/favorites", UserFavoritesView.as_view(), name="user-favorites"),
    path("user/favorites/add", UserFavoritesView.as_view(), name="user-favorites-add"),
    path("user/favorites/remove", UserFavoritesView.as_view(), name="user-favorites-remove"),
    path("user/orders", UserOrdersView.as_view(), name="user-orders"),
    path("user/orders/guest-history", UserOrderGuestHistoryView.as_view(), name="user-order-guest-history"),
    path("user/orders/detail", UserOrdersDetailView.as_view(), name="user-orders-detail"),
    path("user/orders/create", UserOrdersCreateView.as_view(), name="user-orders-create"),
    path("user/orders/update", UserOrdersUpdateView.as_view(), name="user-orders-update"),
    path("user/orders/pay", UserOrdersPayView.as_view(), name="user-orders-pay"),
    path("user/orders/cancel", UserOrdersCancelView.as_view(), name="user-orders-cancel"),
    path("user/reviews/create", UserReviewsCreateView.as_view(), name="user-reviews-create"),
    path("user/points/logs", UserPointsLogsView.as_view(), name="user-points-logs"),
    path("user/notices", UserNoticesView.as_view(), name="user-notices"),
    path("user/notices/unread-count", UserNoticeUnreadCountView.as_view(), name="user-notices-unread-count"),
    path("user/coupons", UserCouponsView.as_view(), name="user-coupons"),
    path("user/coupons/available", UserAvailableCouponsView.as_view(), name="user-coupons-available"),
    path("user/coupons/claim", UserClaimCouponView.as_view(), name="user-coupons-claim"),
    path("user/orders/available-coupons", UserOrderAvailableCouponsView.as_view(), name="user-orders-available-coupons"),
    path("user/invoices", UserInvoicesView.as_view(), name="user-invoices"),
    path("user/invoices/create", UserInvoiceTitleCreateView.as_view(), name="user-invoices-create"),
    path("user/invoices/apply", UserInvoiceApplyView.as_view(), name="user-invoices-apply"),
    path("user/ai/chat", UserAIChatView.as_view(), name="user-ai-chat"),
    path("user/ai/chat/stream", UserAIChatStreamView.as_view(), name="user-ai-chat-stream"),
    # 管理端接口
    path("admin/dashboard/overview", AdminDashboardOverviewView.as_view(), name="admin-dashboard-overview"),
    path("admin/dashboard/charts", AdminDashboardChartsView.as_view(), name="admin-dashboard-charts"),
    path("admin/members/overview", AdminMemberOverviewView.as_view(), name="admin-members-overview"),
    path("admin/coupons", AdminCouponTemplatesView.as_view(), name="admin-coupons"),
    path("admin/coupons/create", AdminCouponTemplatesView.as_view(), name="admin-coupons-create"),
    path("admin/coupons/update", AdminCouponTemplateUpdateView.as_view(), name="admin-coupons-update"),
    path("admin/hotels", AdminHotelsView.as_view(), name="admin-hotels"),
    path("admin/hotels/create", AdminHotelsView.as_view(), name="admin-hotels-create"),
    path("admin/hotels/update", AdminHotelsView.as_view(), name="admin-hotels-update"),
    path("admin/hotels/delete", AdminHotelsView.as_view(), name="admin-hotels-delete"),
    path("admin/room-types", AdminRoomTypesView.as_view(), name="admin-room-types"),
    path("admin/room-types/create", AdminRoomTypesView.as_view(), name="admin-room-types-create"),
    path("admin/room-types/update", AdminRoomTypesView.as_view(), name="admin-room-types-update"),
    path("admin/room-types/delete", AdminRoomTypesView.as_view(), name="admin-room-types-delete"),
    path("admin/inventory/calendar", AdminInventoryView.as_view(), name="admin-inventory-calendar"),
    path("admin/inventory/update", AdminInventoryView.as_view(), name="admin-inventory-update"),
    path("admin/orders", AdminOrdersView.as_view(), name="admin-orders"),
    path("admin/orders/detail", AdminOrdersDetailView.as_view(), name="admin-orders-detail"),
    path("admin/orders/change-status", AdminOrdersChangeStatusView.as_view(), name="admin-orders-change-status"),
    path("admin/orders/check-in", AdminOrdersCheckInView.as_view(), name="admin-orders-check-in"),
    path("admin/orders/check-out", AdminOrdersCheckOutView.as_view(), name="admin-orders-check-out"),
    path("admin/reviews", AdminReviewsView.as_view(), name="admin-reviews"),
    path("admin/reviews/reply", AdminReviewsReplyView.as_view(), name="admin-reviews-reply"),
    path("admin/reports/tasks", AdminReportTasksView.as_view(), name="admin-report-tasks"),
    path("admin/reports/tasks/create", AdminReportTasksView.as_view(), name="admin-report-tasks-create"),
    path("admin/users", AdminUsersView.as_view(), name="admin-users"),
    path("admin/users/change-status", AdminUsersChangeStatusView.as_view(), name="admin-users-change-status"),
    path("admin/employees", AdminEmployeesView.as_view(), name="admin-employees"),
    path("admin/employees/create", AdminEmployeesView.as_view(), name="admin-employees-create"),
    path("admin/settings", AdminSettingsView.as_view(), name="admin-settings"),
    path("admin/settings/update", AdminSettingsView.as_view(), name="admin-settings-update"),
    path("admin/ai/report-summary", AdminAIReportSummaryView.as_view(), name="admin-ai-report-summary"),
    path("admin/ai/review-summary", AdminAIReviewSummaryView.as_view(), name="admin-ai-review-summary"),
    path("admin/ai/reply-suggestion", AdminAIReplySuggestionView.as_view(), name="admin-ai-reply-suggestion"),
    path("admin/ai/settings", AdminAISettingsView.as_view(), name="admin-ai-settings"),
    path("admin/ai/settings/update", AdminAISettingsView.as_view(), name="admin-ai-settings-update"),
    path("admin/ai/provider/add", AdminAIProviderAddView.as_view(), name="admin-ai-provider-add"),
    path("admin/ai/provider/switch", AdminAIProviderSwitchView.as_view(), name="admin-ai-provider-switch"),
    path("admin/ai/provider/delete", AdminAIProviderDeleteView.as_view(), name="admin-ai-provider-delete"),
    # 系统重置接口
    path("admin/system/reset", AdminSystemResetView.as_view(), name="admin-system-reset"),
]
