# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_type", models.CharField(choices=[("revenue_summary", "营收报表"), ("order_summary", "订单报表"), ("review_summary", "评价报表")], default="revenue_summary", max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("status", models.CharField(choices=[("pending", "待处理"), ("running", "执行中"), ("success", "成功"), ("failed", "失败")], default="pending", max_length=20)),
                ("result_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hotel", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name="report_tasks", to="hotels.hotel")),
            ],
            options={
                "verbose_name": "Report Task",
                "verbose_name_plural": "Report Tasks",
                "ordering": ["-id"],
            },
        ),
    ]
