# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_no", models.CharField(max_length=64, unique=True)),
                ("method", models.CharField(choices=[("mock", "模拟支付"), ("wechat", "微信支付"), ("alipay", "支付宝"), ("cash", "现金"), ("card", "银行卡")], default="mock", max_length=20)),
                ("status", models.CharField(choices=[("unpaid", "未支付"), ("paid", "已支付"), ("failed", "支付失败"), ("refunded", "已退款")], default="unpaid", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="payments", to="bookings.bookingorder")),
            ],
            options={
                "verbose_name": "Payment Record",
                "verbose_name_plural": "Payment Records",
                "ordering": ["-id"],
            },
        ),
    ]
