# Generated by Django 6.0.3 on 2026-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunding', '退款中'), ('refunded', '已退款')], default='unpaid', max_length=20),
        ),
    ]
