# Generated by Django 6.0.3 on 2026-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paymentrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="external_trade_no",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="gateway_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="gateway_name",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="notify_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="provider_type",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="scene",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="method",
            field=models.CharField(
                choices=[
                    ("mock", "模拟支付"),
                    ("wechat", "微信支付"),
                    ("alipay", "支付宝"),
                    ("custom", "其他支付平台"),
                    ("cash", "现金"),
                    ("card", "银行卡"),
                ],
                default="mock",
                max_length=20,
            ),
        ),
    ]
